import { MouseEventHandler, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "@/components/RandomFox";

// generate simple unique id
const generateId = (): string => {
  return (
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15)
  );
};

// random number from 1 to 122
const random = () => Math.floor(Math.random() * 122) + 1;

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox:MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem:ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    }
    setImages([
      ...images,
      newImageItem
    ])
  }
  
  type ImageItem = {
    id: string;
    url: string;
  };
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello Platzi!</h1>
        <button onClick={addNewFox}>Add new fox</button>
        {images.map(({ id, url }) => (
          <div className="p-4" key={id}>
            <RandomFox image={url} />
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
