import { MouseEventHandler, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "@/components/LazyImage";
import { random } from 'lodash'
// generate simple unique id
const generateId = (): string => {
  return (
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15)
  );
};

// random number from 1 to 122
const myRandom = () => random(1, 123);

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<IImageItem>>([]);

  const addNewFox:MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem:IImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${myRandom()}.jpg`
    }
    setImages([
      ...images,
      newImageItem
    ])
  }
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello Platzi!</h1>
        <button onClick={addNewFox}>Add new fox</button>
        {images.map(({ id, url }, index) => (
          <div className="p-4" key={id}>
          <LazyImage
            src={url}
            width="320"
            height="auto"
            className="mx-auto rounded-md bg-gray-300"
            onClick={() => {
              console.log("test");
            }}
            onLazyLoad={(img) => {
              console.log(`Image #${index + 1} cargada. Nodo:`, img);
            }}
          />
        </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
